### ISSUE TITLE
can't import MechEye

### ISSUE THREAD

**Issue by sloth-cn** [MechMindRobotics/mecheye_python_samples#1]
follow the ReadMe to install software on windows.
1. python version is 3.7.2. 
2. install SDK1.5.2.1.6.9
3. pip install MechEyeAPI (1.5.2.1.6.9)
test env:
1. open python shell by input ‘python’ on cmd env.
2. input 'from MechEye import Device'
below is error info:
![image](https://user-images.githubusercontent.com/41658286/167079655-e8b720ce-0694-4f10-add6-52ff4bb11ab0.png)

![image](https://user-images.githubusercontent.com/41658286/167079023-17047105-0dfd-4243-b4b2-310179d27dc1.png)

  
I verified the three setting. all of them are ok. So pls check what is the problem

**Comment by YoungYan-0** [comment]
Hi sloth!

 I double checked on my own computer with Python 3.7 and it worked fine. Have you intalled the Mech-Eye SDK_1.5.2 from https://www.mech-mind.com/download/camera-sdk.html?

**Comment by sloth-cn** [comment]
yes, i installed this version SDK follow README. and i try to set up the env on different PC, all pc didn’t work and show same error like the picture i attached.

finally i give up to use it on windows. switch to Linux os, env set up and work fine.


发自我的iPhone

**Comment by YoungYan-0** [comment]
![89D55FE0-5680-4bf1-9BA1-83CE720A7931](https://user-images.githubusercontent.com/58017535/167238470-d1218eee-e6ba-42f4-a156-d35ac6e89938.png)
Do you have these two environment variables after installing the SDK on Windows?

**Comment by sloth-cn** [comment]
yes, my env have these two environment variables.

another question,  where is the download link for camera firmware download?  I need upgrade my camera firmware version from V1.4.3 to V1.5.2. Many thanks.

**Comment by YoungYan-0** [comment]
Do you have your python added to path?

You can upgrade your camera firmware in Mech-Eye Viewer by clicking Tools->Camera Firmware Upgrade.

**Comment by sloth-cn** [comment]
yes, I can run python in CMD by input command “python”

**Comment by sloth-cn** [comment]
> Do you have your python added to path?
> 
> You can upgrade your camera firmware in Mech-Eye Viewer by clicking Tools->Camera Firmware Upgrade.

I know how to upgrade, I don't know is that where is the firmware  file?

**Comment by YoungYan-0** [comment]
The firmware files are in the install folder/resource_runtime/for_update folder

**Comment by sloth-cn** [comment]
thanks, finally, I figure out that the firmware was included in SDK, not a independent release file.

**Comment by sloth-cn** [comment]
Right now, I have to work on Linux. Windows still not work.  if you need more info, pls let me know.

**Comment by YoungYan-0** [comment]
Do you have any older version of our SDK installed on your machine? Before version 1.5.2, our SDK is installed in C:/mmind by default, which may affect the env variables.

**Comment by sloth-cn** [comment]
No, Actually, in order to install SDK, I reinstall windows OS on PC. but still not work

**Comment by YoungYan-0** [comment]
I encountered this issue on another PC, I tried to remove the __init__.py from the PythonInstallFolder/Lib/site-packages/_MechEye/, and it works.
Maybe you can try this. 
I will try on other computers and fix this soon.

**Comment by YoungYan-0** [comment]
\__init\__.py

**Comment by YoungYan-0** [comment]
Have you installed other versions of Python before? 
I encountered this issue on another PC which I uninstalled the Python3.6.8 to install Python3.7.2. After removing Python3.6 related environment variables, it works fine. So maybe you can try to remove the environment variables related to previous versions of Python.

**Comment by sloth-cn** [comment]
As i said before, I reinstall windows OS, then install software (python, Mech SDK, MechEyeAPI ) on the totally new OS.  So the issue is not relate to previous version Python, because there is no previous version Python after i reinstall Windows OS.

**Comment by YoungYan-0** [comment]
![image](https://user-images.githubusercontent.com/58017535/167326512-7704be15-a1d9-4754-9a56-0da904b823f1.png)
Adding these two paths from the `MECHEYE_DLL_PATH` variable to the `Path` environment variable may solve this problem. If it works, I will update the README immediately.
