### ISSUE TITLE
Processing in samples not efficient

### ISSUE THREAD

**Issue by NoahS-Magna** [MechMindRobotics/mecheye_python_samples#4]
There is a very inefficient code snippet (example copied below) that is being reused in every sample program that captures a pointcloud in this repo. It is taking my machine roughly 7 seconds to get through it wherever it shows up.

Original (from CaptureHDRPointCloud.py):
```python
        point_xyz_data = point_xyz.data()

        point_cloud_xyz = o3d.geometry.PointCloud()
        points_xyz = np.zeros(
            (point_xyz.width() * point_xyz.height(), 3), dtype=np.float64)

        pos = 0
        for dd in np.nditer(point_xyz_data):
            points_xyz[int(pos / 3)][int(pos % 3)] = 0.001 * dd
            pos = pos + 1
```
The `for` loop sequentially executes once for every point in the data--over 2 million iterations. This can be done much faster (~7000x on my machine) by taking advantage of the numpy library which is much faster than pure python. The above section can be condensed to the following:
```python
        point_xyz_data = point_xyz.data()

        point_cloud_xyz = o3d.geometry.PointCloud()
        points_xyz = point_cloud_xyz.reshape(-1, 3) * 0.001
```
A similar change can be made further down when the color data is processed.

With the above fix, processing time after the scan is complete becomes almost negligible. Sample files where this can be applied:
- CapturePointCloud
- CaptureHDRPointCloud
- CapturePointCloudROI
- CaptureCloudFromDepth

**Comment by shuaidang** [comment]
Thanks for your feedback, the issue has been fixed in a new version
