### ISSUE TITLE
python API package code contains a bug in Windows

### ISSUE THREAD

**Issue by SamDM** [MechMindRobotics/mecheye_python_samples#5]
# How to reproduce

1. Get a windows 10 machine.
2. Download the SDK package version 1.5.2, verify that you can take images with Mech-Eye viewer.
3. Install the python package (version 1.5.2.1.6.9) in a python env above python 3.8.
5. try to run [this script](https://github.com/MechMindRobotics/mecheye_python_samples/blob/8e1f1824bacc329b330f0f29770e742aaf42ebab/source/Basic/ConnectAndCaptureImage.py).

This will happen:
```
Traceback (most recent call last):
  File "c:\Users\SamDM-win10\Documents\mecheye_python_samples\source\Basic\ConnectAndCaptureImage.py", line 1, in <module>
    from MechEye import Device
  File "C:\Users\SamDM-win10\miniconda3\envs\MechEye\lib\site-packages\MechEye\__init__.py", line 6, in <module>
    from MechEye.device import Device
  File "C:\Users\SamDM-win10\miniconda3\envs\MechEye\lib\site-packages\MechEye\device.py", line 1, in <module>
    import _MechEye
  File "C:\Users\SamDM-win10\miniconda3\envs\MechEye\lib\site-packages\_MechEye\__init__.py", line 33, in <module>
    assert len(pyd_files) == 1
AssertionError
```

# Why this happens

Of course this happens 🤷🏻‍♂️ , the python package installation provides the following files:
```
C:\Users\SamDM-win10\miniconda3\envs\MechEye\lib\site-packages\_MechEye\_MechEye.cp310-win_amd64.pyd
C:\Users\SamDM-win10\miniconda3\envs\MechEye\lib\site-packages\_MechEye\_MechEye.cp36-win_amd64.pyd
C:\Users\SamDM-win10\miniconda3\envs\MechEye\lib\site-packages\_MechEye\_MechEye.cp37-win_amd64.pyd
C:\Users\SamDM-win10\miniconda3\envs\MechEye\lib\site-packages\_MechEye\_MechEye.cp38-win_amd64.pyd
C:\Users\SamDM-win10\miniconda3\envs\MechEye\lib\site-packages\_MechEye\_MechEye.cp39-win_amd64.pyd
```

# How to fix it

In `c:\Users\SamDM-win10\miniconda3\envs\MechEye\Lib\site-packages_MechEye_init_.py` line 39,
add the following  lines:
(adjust the path above to your situation of course)

```
    version_str = f"cp{sys.version_info.major}{sys.version_info.minor}"
    pyd_files = [p for p in package_dir.glob("_MechEye*.pyd") if version_str in str(p)]
```

This will select the appropriate file for your python version.
After this, the library seems to function properly.

**Comment by shuaidang** [comment]
Hello, you can use the latest version of the MechEye API, which is version 2.1.0, and it has significant optimizations compared to previous versions.
